apiVersion: v1
kind: Service
metadata:
  name: redis-master
  namespace: {{ .Values.namespace }}
  labels:
    app: redis
    role: master
spec:
  ports:
  - port: {{ .Values.redis.port }}
    targetPort: redis-server
  selector:
    app: redis
    role: master
